# -*- coding: utf-8 -*-
"""Gráfico de barras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ueV_reTsVNh4N0onaDcocWVaAiXK7k7
"""

import pandas as pd
import matplotlib.pyplot as plt

# importar dados para dataframe
df = pd.read_csv("https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/entrada_passageiro_linha1.csv")

df.head()

df.dtypes

df.tail()

df.drop(index=23, axis=0, inplace=True)

df.tail()

df.plot("Estação", "Entradas", kind = 'bar')
plt.title('Entrada média de passageiros')
plt.xlabel('Estação')
plt.xlabel('Entradas')

plt.show()

