# -*- coding: utf-8 -*-
"""Boxplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B8_Ky2cSe16zzV5sJb-G59sJ1byOFZLd
"""

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/dengue-dataset.csv")

df.head()

df.boxplot(['temperatura-media','temperatura-mininima','temperatura-maxima'])
plt.show()

df.boxplot(['casos-confirmados'], vert = False)
plt.show()

df.loc[df['casos-confirmados'] < 150].boxplot(['casos-confirmados'], vert = False)
plt.show()

