# -*- coding: utf-8 -*-
"""Gráfico de pizza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CkR5EOVsk0YWwy2oHoujGqop4mqq3VlG
"""

import pandas as pd
import matplotlib.pyplot as plt

# importar o arquivo csv
df = pd.read_csv("https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/ocorrencias_aviacao.csv")

df.head()

df['ocorrencia_classificacao'].value_counts()

rotulo = ['INCIDENTE','ACIDENTE','INCIDENTE GRAVE']
valores = [2861, 1714, 633]
plt.pie(valores, labels = rotulo)

a = dict(df['ocorrencia_classificacao'].value_counts())

a

rotulo = a.keys()
valores = a.values()

plt.pie(valores, labels = rotulo)

espassamento = (0.1, 0.1, 0.1)
plt.pie(valores, explode = espassamento, labels = rotulo)

