# -*- coding: utf-8 -*-
"""Gráfico de Dispersão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1DPIql1QjuJrJ0lqL2U77gVhiE2tD5f
"""

import pandas as pd
import matplotlib.pyplot as plt

# importar o dataset
df = pd.read_csv("https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/housing.csv")

df.head()

df.plot.scatter('median_income', 'median_house_value',  s=0.001)
plt.show()

