# -*- coding: utf-8 -*-
"""Gráfico de Waffle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yz3BJqw23o0OJD4m6XyHcNcc1zJv3jae
"""

!pip install pywaffle -q

import matplotlib.pyplot as plt
from pywaffle import Waffle

fig = plt.figure(
                FigureClass=Waffle,
                rows=4,
                columns=10,
                values={'Bolacha': 33,
                        'Biscoito': 48,
                        'Salgadinho': 19},
                legend={'loc': 'upper left',
                        'bbox_to_anchor': (1.1, 1)}
                )


plt.show()

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/ocorrencias_aviacao.csv")

data = dict(df["ocorrencia_classificacao"].value_counts())

data

fig = plt.figure(
                FigureClass=Waffle,
                rows=5,
                columns=15,
                colors=("#232066", "#983D3D", "#DCB732"),
                values=data, icons='laptop', icon_size=12,
                legend={'loc': 'upper left', 'bbox_to_anchor': (1,1)},
                icon_legend=True
                )
fig.set_tight_layout(False)
plt.show();

fig = plt.figure(
                FigureClass=Waffle,
                rows=5,
                columns=15,
                colors=("#232066", "#983D3D", "#DCB732"),
                values=data, icons='plane', icon_size=12,
                legend={'loc': 'upper left', 'bbox_to_anchor': (1,1)},
                icon_legend=True
                )
fig.set_tight_layout(False)
plt.show();

fig = plt.figure(
                FigureClass=Waffle,
                rows=5,
                columns=16,
                colors=("#145A32", "#FF0000", "#FFD700"),
                values={'Com Agente: 4547': 4547,
                        'Sem Agente: 564': 564,
                        'Não localizado: 473': 473
                        }, 
                
                icons='laptop', icon_size=12,
                legend={'loc': 'upper left', 'bbox_to_anchor': (1.1,1)},
                title={'label': 'Contagens'}, 
                icon_legend=True
                )
fig.set_tight_layout(False)
plt.show();

round(23.624489795918, 2)

